Necromorphs
WestHybrid/DS13-TG pull request #6
Opened 2022-05-23 06:37 UTC by DTraitor

## About The Pull Request

Removed vector lib completely, we are not going to use it at all.
Implemented basic necromorph type, other necromorphs should be it's subtypes.
Necromorphs don't have proper health bar, I'm waiting for Ketrai's sprites.
Basic necromorph lack a lot of functions (I will continue working on necromorphs after this PR), the only reason I'm PR'ing it is to fix some compile issues and to let other devs continue their work.

P.S. Some changes in external organs code are Kapu's changes from /tg/

2022-05-23 15:59 UTC, DeadLineSS13 requested changes
Есть вопросы и предложения

2022-05-26 17:11 UTC, DeadLineSS13 commented on code/modules/mob/living/carbon/carbon_defense.dm
> +	/*
Я бы честно удалил бы это...

2022-05-26 17:19 UTC, DeadLineSS13 requested changes
Есть некоторые недочёты, а так нужно пообсуждать некоторые темы точн.

2022-05-26 17:19 UTC, DeadLineSS13 commented on code/modules/surgery/bodyparts/species_parts/lizard_bodyparts.dm
> -	bodytype = BODYTYPE_HUMANOID | BODYTYPE_ORGANIC | BODYTYPE_SNOUTED //This is temporary. Ideally the "snout" external organ adds to this.
А куда это?

2022-05-26 17:19 UTC, DeadLineSS13 commented on necromorphs/code/__DEFINES/is_helpers.dm
> +/mob/dead/observer/eye/signal
А шо это делает тут?

2022-05-26 17:19 UTC, DeadLineSS13 commented on necromorphs/code/__DEFINES/traits.dm
> +#define NECROMORPH_TRAIT "necromorph"
Даже лучше чем будет проверка is_necromorph

2022-05-26 17:19 UTC, DeadLineSS13 commented on necromorphs/code/marker/marker.dm
> +	for(var/datum/necro_class/class as anything in subtypesof(/datum/necro_class))
Надо поэкспериментировать попробывать возмжно ли сделать так, чтобы нужные значение назначались на necro_class c /mob/living/carbon/necromorph. Типо у нас часть переменных в датуме и мы принимаем значение эти с прямого каждого подмоба Некроморфа

2022-05-26 17:19 UTC, DeadLineSS13 commented on necromorphs/code/marker/marker_status.dm
> +/datum/marker_status/proc/necro_removed(mob/living/carbon/necromorph/N)
Ну если меняешь, то сделай N => necro

2022-05-26 17:19 UTC, DeadLineSS13 commented on necromorphs/code/necromorph/hud/hud.dm
> +//Health meter
А это работает?

2022-05-26 17:22 UTC, DTraitor commented on code/modules/surgery/bodyparts/species_parts/lizard_bodyparts.dm
> -	bodytype = BODYTYPE_HUMANOID | BODYTYPE_ORGANIC | BODYTYPE_SNOUTED //This is temporary. Ideally the "snout" external organ adds to this.
Это часть изменений из ТГ (они недавно переделывали конечности, а это чуть позже замержили)
> P.S. Some changes in external organs code are Kapu's changes from /tg/

2022-05-26 17:22 UTC, DTraitor commented on necromorphs/code/__DEFINES/is_helpers.dm
> +/mob/dead/observer/eye/signal
фикс компиляции ибо проверки все равно нужны, уберешь потом когда сигналы будут

2022-05-26 17:23 UTC, DTraitor commented on necromorphs/code/__DEFINES/traits.dm
> +#define NECROMORPH_TRAIT "necromorph"
это источник конечно, но идея толковая, заменю пожалуй все `is_necromorph()` на проверку трейта

2022-05-26 17:24 UTC, DTraitor commented on necromorphs/code/marker/marker_status.dm
> +/datum/marker_status/proc/necro_removed(mob/living/carbon/necromorph/N)
не заметил

2022-05-26 17:24 UTC, DTraitor commented on necromorphs/code/necromorph/hud/hud.dm
> +//Health meter
нет, жду спрайты от Кетраи

2022-05-29 14:10 UTC, merged